
version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - chainpoint-node
    environment:
      NODE_ENV: ${NODE_ENV}
      NETWORK: ${NETWORK}
      HTTP_PORT: "${HTTP_PORT:-80}"
      HTTPS_PORT: "${HTTPS_PORT:-443}"
      AUTO_REFILL_ENABLED: "${AUTO_REFILL_ENABLED:-true}"
      AUTO_REFILL_AMOUNT: "${AUTO_REFILL_AMOUNT:-720}"
      NODE_ETH_ADDRESS: "${NODE_ETH_ADDRESS}"
      NODE_ETH_PRIVATE_KEY: "${NODE_ETH_PRIVATE_KEY}"
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_NODE_PRIVATE_URI: "${CHAINPOINT_NODE_PRIVATE_URI:-empty}"
      CHAINPOINT_NODE_REFLECT_PUBLIC_OR_PRIVATE: "${CHAINPOINT_NODE_REFLECT_PUBLIC_OR_PRIVATE}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      CHAINPOINT_NODE_UI_PASSWORD: "${CHAINPOINT_NODE_UI_PASSWORD:-empty}"
      PRIVATE_NETWORK: ${PRIVATE_NETWORK:-false}
    tty: true
