
version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ./keys:/home/node/app/keys
      - ./.data/rocksdb:/home/node/app/.data/rocksdb
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - chainpoint-node
    environment:
      HTTP_PORT: "${HTTP_PORT:-8080}"
      HTTPS_PORT: "${HTTPS_PORT:-8443}"
      NODE_ETH_ADDRESS: "${NODE_ETH_ADDRESS}"
      NODE_ETH_PRIVATE_KEY: "${NODE_ETH_PRIVATE_KEY}"
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_CORE_API_BASE_URI: "${CHAINPOINT_CORE_API_BASE_URI:-http://35.245.211.97}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST:-http://35.245.211.97}"
      CHAINPOINT_NODE_UI_PASSWORD: "${CHAINPOINT_NODE_UI_PASSWORD:-empty}"
