
version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
    build: .
    ports:
      - "80:80"
    networks:
      - chainpoint-node
    environment:
      NODE_ENV: ${NODE_ENV}
      NETWORK: ${NETWORK}
      HTTP_PORT: "${HTTP_PORT:-80}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
    tty: true
