version: "3.4"

networks:
  chainpoint-node:
    driver: bridge

services:
  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
    build: .
    ports:
      - "80:80"
    networks:
      - chainpoint-node
    environment:
      LND_SOCKET: "lnd:10009"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      CHAINPOINT_NODE_HTTP_PORT: "${CHAINPOINT_NODE_HTTP_PORT}"
      AGGREGATION_INTERVAL_SECONDS: "${AGGREGATION_INTERVAL_SECONDS}"
      PROOF_EXPIRE_MINUTES: "${PROOF_EXPIRE_MINUTES}"
      POST_HASHES_MAX: "${POST_HASHES_MAX}"
      POST_VERIFY_PROOFS_MAX: "${POST_VERIFY_PROOFS_MAX}"
      GET_PROOFS_MAX: "${GET_PROOFS_MAX}"
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
    tty: true

  # Lightning node
  lnd:
    image: tierion/lnd:latest
    user: ${USERID}:${GROUPID}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 9735
        published: 9735
        protocol: tcp
        mode: host
      - target: 10009
        published: 10009
        protocol: tcp
        mode: host
    restart: always
    environment:
      - PUBLICIP=${NODE_RAW_IP}
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG=info
      - NEUTRINO
      - LND_REST_PORT
      - LND_RPC_PORT
      - TLSPATH
    volumes:
      - ~/.lnd/chainpoint-node:/root/.lnd:z
    networks:
      - chainpoint-node
