version: "3.4"

networks:
  chainpoint-node:
    driver: bridge

services:
  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ~/.chainpoint/node/.lnd:/root/.lnd:ro
    build: .
    container_name: chainpoint-node
    ports:
      - "80:8080"
    networks:
      - chainpoint-node
    environment:
      HOME: /root
      HOT_WALLET_PASS: ${HOT_WALLET_PASS}
      LND_SOCKET: ${LND_SOCKET}
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      AGGREGATION_INTERVAL_SECONDS: "${AGGREGATION_INTERVAL_SECONDS}"
      PROOF_EXPIRE_MINUTES: "${PROOF_EXPIRE_MINUTES}"
      POST_HASHES_MAX: "${POST_HASHES_MAX}"
      POST_VERIFY_PROOFS_MAX: "${POST_VERIFY_PROOFS_MAX}"
      GET_PROOFS_MAX: "${GET_PROOFS_MAX}"
      MAX_SATOSHI_PER_HASH: "${MAX_SATOSHI_PER_HASH}"
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
    tty: true

  # Lightning node
  lnd:
    image: tierion/lnd:boltbox
    user: ${USERID}:${GROUPID}
    entrypoint: "./start-lnd.sh"
    container_name: lnd-node
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 9735
        published: 9735
        protocol: tcp
        mode: host
      - target: 10009
        published: 10009
        protocol: tcp
        mode: host
    restart: always
    environment:
      - PUBLICIP=${LND_PUBLIC_IP}
      - RPCUSER
      - RPCPASS
      - NETWORK=${NETWORK:-testnet}
      - CHAIN
      - DEBUG=info
      - BACKEND=neutrino
      - NEUTRINO=faucet.lightning.community:18333
      - LND_REST_PORT
      - LND_RPC_PORT
      - TLSPATH
      - TLSEXTRADOMAIN=lnd
    volumes:
      - ~/.chainpoint/node/.lnd:/lnd-data:z
    networks:
      - chainpoint-node
