version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  postgres:
    image: postgres:9.6.9-alpine
    container_name: postgres-node-src
    restart: always
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chainpoint
      POSTGRES_PASSWORD: chainpoint
    networks:
      - chainpoint-node

  chainpoint-node:
    image: gcr.io/chainpoint-registry/chainpoint-node:latest
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ./keys:/home/node/app/keys
      - ./.data/rocksdb:/home/node/app/rocksdb
    build: .
    ports:
      - "9090:8080"
    networks:
      - chainpoint-node
    depends_on:
      - postgres
    environment:
      NODE_TNT_ADDRESS: "${NODE_TNT_ADDRESS}"
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_CORE_API_BASE_URI: "${CHAINPOINT_CORE_API_BASE_URI:-http://0.0.0.0}"
      CHAINPOINT_NODE_UI_PASSWORD: "${CHAINPOINT_NODE_UI_PASSWORD:-empty}"
      #DEBUG: "sequelize*"
