version: '3.4'

networks:
  chainpoint-node:
    driver: bridge
  # Useful networks for local dev/testing
  chainpoint-core_chainpoint:
    external: true
  boltbox-simnet:
    external: true

services:
  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ~/.chainpoint/node/.lnd:/root/.lnd:ro
    build: .
    container_name: chainpoint-node
    ports:
      # - '${PORT}:${CHAINPOINT_NODE_PORT}'
      - '80:8080'
    networks:
      - chainpoint-node
      - boltbox-simnet
      - chainpoint-core_chainpoint
    environment:
      HOME: /root
      HOT_WALLET_PASS: ${HOT_WALLET_PASS}
      LND_SOCKET: ${LND_SOCKET}
      LND_MACAROON: ${LND_MACAROON}
      LND_TLS_CERT: ${LND_TLS_CERT}
      CHAINPOINT_CORE_CONNECT_IP_LIST: '${CHAINPOINT_CORE_CONNECT_IP_LIST}'
      PORT: '${PORT:-80}'
      AGGREGATION_INTERVAL_SECONDS: '${AGGREGATION_INTERVAL_SECONDS}'
      PROOF_EXPIRE_MINUTES: '${PROOF_EXPIRE_MINUTES}'
      CHAINPOINT_NODE_PORT: '${CHAINPOINT_NODE_PORT:-9090}'
      POST_HASHES_MAX: '${POST_HASHES_MAX}'
      POST_VERIFY_PROOFS_MAX: '${POST_VERIFY_PROOFS_MAX}'
      GET_PROOFS_MAX: '${GET_PROOFS_MAX}'
      MAX_SATOSHI_PER_HASH: '${MAX_SATOSHI_PER_HASH}'
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
    tty: true

  # Lightning node
  lnd:
    image: tierion/lnd:boltbox
    user: ${USERID}:${GROUPID}
    entrypoint: './start-lnd.sh'
    container_name: lnd-node
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 9735
        published: 9735
        protocol: tcp
        mode: host
      - target: 10009
        published: 10009
        protocol: tcp
        mode: host
    restart: always
    environment:
      - PUBLICIP=${LND_PUBLIC_IP}
      - RPCUSER
      - RPCPASS
      - NETWORK=${NETWORK:-testnet}
      - CHAIN
      - DEBUG=info
      - BACKEND=neutrino
      - NEUTRINO=faucet.lightning.community:18333
      - LND_REST_PORT
      - LND_RPC_PORT
      - TLSPATH
      - TLSEXTRADOMAIN=lnd
    volumes:
      - ~/.chainpoint/node/.lnd:/root/.lnd:z
    networks:
      - chainpoint-node

  # ln-accounting
  # Returns accounting reports in harmony format for lnd node
  ln-accounting:
    image: tierion/ln-accounting
    ports:
      - '9000'
    environment:
      NETWORK: ${NETWORK}
      LND_DIR: /root/.lnd
      LND_SOCKET: ${LND_SOCKET}
      ACCOUNTING_PORT: ${ACCOUNTING_PORT:-9000}
    volumes:
      - ~/.chainpoint/node/.lnd:/root/.lnd:ro
    networks:
      - chainpoint-node
