version: "3.7"

networks:
  chainpoint-node:

secrets:

services:
  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ./.env:/home/node/app/.env
      - ~/.lnd:/root/.lnd:ro
    image: gcr.io/chainpoint-registry/github_chainpoint_chainpoint-node-src:${DOCKER_TAG:-latest}
    build: .
    depends_on:
      - lnd
    ports:
      - "80:80"
    networks:
      - chainpoint-node
    environment:
      LND_TLS_CERT: "${LND_TLS_CERT}"
      LND_MACAROON: "${LND_MACAROON}"
      LND_SOCKET: "${LND_TLS_CERT}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      CHAINPOINT_NODE_HTTP_PORT: "${CHAINPOINT_NODE_HTTP_PORT}"
      AGGREGATION_INTERVAL_SECONDS: "${AGGREGATION_INTERVAL_SECONDS}"
      PROOF_EXPIRE_MINUTES: "${PROOF_EXPIRE_MINUTES}"
      POST_HASHES_MAX: "${POST_HASHES_MAX}"
      POST_VERIFY_PROOFS_MAX: "${POST_VERIFY_PROOFS_MAX}"
      GET_PROOFS_MAX: "${GET_PROOFS_MAX}"
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
    secrets:
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:27635"
        tag: "chp-node/{{.Name}}/{{.ID}}"

  # Lightning node
  lnd:
    image: tierion/lnd:latest
    user: ${USERID}:${GROUPID}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 9735
        published: 9735
        protocol: tcp
        mode: host
      - target: 10009
        published: 10009
        protocol: tcp
        mode: host
    restart: always
    environment:
      - PUBLICIP
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - NEUTRINO
      - LND_REST_PORT
      - LND_RPC_PORT
      - TLSPATH
    volumes:
      - ~/.lnd:/root/.lnd:z
    networks:
      - chainpoint-node
