version: '3.7'

networks:
  chainpoint-node:

secrets:

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ./.env:/home/node/app/.env
    image: gcr.io/chainpoint-registry/github_chainpoint_chainpoint-node-src:${DOCKER_TAG:-latest}
    build: .
    ports:
      - "80:80"
    networks:
      - chainpoint-node
    environment:
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      CHAINPOINT_NODE_HTTP_PORT: "${CHAINPOINT_NODE_HTTP_PORT}"
      PROOF_EXPIRE_MINUTES: "${PROOF_EXPIRE_MINUTES}"
      POST_HASHES_MAX: "${POST_HASHES_MAX}"
      POST_VERIFY_PROOFS_MAX: "${POST_VERIFY_PROOFS_MAX}"
      GET_PROOFS_MAX: "${GET_PROOFS_MAX}"
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
    secrets:
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:27635"
        tag: "chp-node/{{.Name}}/{{.ID}}"
