version: '3.7'

networks:
  chainpoint-node:

secrets:
  NODE_ETH_ADDRESS:
    external: true
  NODE_ETH_PRIVATE_KEY:
    external: true

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ./.data/rocksdb:/home/node/app/.data/rocksdb
      - ./.env:/home/node/app/.env
    image: gcr.io/chainpoint-registry/github-chainpoint-chainpoint-node-src:latest
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - chainpoint-node
    environment:
      HTTP_PORT: "${HTTP_PORT:-80}"
      HTTPS_PORT: "${HTTPS_PORT:-8443}"
      NODE_ETH_ADDRESS: DOCKER-SECRET->NODE_ETH_ADDRESS
      NODE_ETH_PRIVATE_KEY: DOCKER-SECRET->NODE_ETH_PRIVATE_KEY
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_CORE_API_BASE_URI: "${CHAINPOINT_CORE_API_BASE_URI:-35.245.211.97}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST:-35.245.211.97}"
      CHAINPOINT_NODE_UI_PASSWORD: "${CHAINPOINT_NODE_UI_PASSWORD:-empty}"
    secrets:
      - NODE_ETH_ADDRESS
      - NODE_ETH_PRIVATE_KEY
    tty: true
