version: "3.7"

networks:
  chainpoint-gateway:

secrets:
  HOT_WALLET_PASS:
    external: true
  HOT_WALLET_ADDRESS:
    external: true

services:
  chainpoint-gateway:
    restart: on-failure
    entrypoint: /home/node/app/scripts/run_prod.sh
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/gateway/data/rocksdb:/root/.chainpoint/gateway/data/rocksdb
      - ./.env:/home/node/app/.env
      - ~/.chainpoint/gateway/.lnd:/root/.lnd:ro
    image: gcr.io/chainpoint-registry/github_chainpoint_chainpoint-gateway:${DOCKER_TAG:-latest}
    user: ${USERID}:${GROUPID}
    build: .
    depends_on:
      - lnd
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
    networks:
      - chainpoint-gateway
    secrets:
      - HOT_WALLET_PASS
      - HOT_WALLET_ADDRESS
    environment:
      HOME: /root
      HOT_WALLET_PASS: DOCKER-SECRET->HOT_WALLET_PASS
      HOT_WALLET_ADDRESS: DOCKER-SECRET->HOT_WALLET_ADDRESS
      LND_SOCKET: ${LND_SOCKET}
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      AGGREGATION_INTERVAL_SECONDS: "${AGGREGATION_INTERVAL_SECONDS}"
      PROOF_EXPIRE_MINUTES: "${PROOF_EXPIRE_MINUTES}"
      POST_HASHES_MAX: "${POST_HASHES_MAX}"
      POST_VERIFY_PROOFS_MAX: "${POST_VERIFY_PROOFS_MAX}"
      GET_PROOFS_MAX: "${GET_PROOFS_MAX}"
      MAX_SATOSHI_PER_HASH: "${MAX_SATOSHI_PER_HASH}"
      NETWORK: ${NETWORK}
      NODE_ENV: ${NODE_ENV}
      CHANNEL_AMOUNT: ${CHANNEL_AMOUNT}
      FUND_AMOUNT: ${FUND_AMOUNT}
      NO_LSAT_CORE_WHITELIST: ${NO_LSAT_CORE_WHITELIST}
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '1g'
        max-file: '5'

  # Lightning node
  lnd:
    image: tierion/lnd:${NETWORK:-testnet}
    user: ${USERID}:${GROUPID}
    entrypoint: "./start-lnd.sh"
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
      mode: host
    - target: 9735
      published: 9735
      protocol: tcp
      mode: host
    - target: 10009
      published: 10009
      protocol: tcp
      mode: host
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 15
        window: 90s
      endpoint_mode: dnsrr
    environment:
      - PUBLICIP=${LND_PUBLIC_IP}
      - RPCUSER
      - RPCPASS
      - NETWORK=${NETWORK:-testnet}
      - CHAIN
      - DEBUG=info
      - BACKEND=neutrino
      - NEUTRINO=faucet.lightning.community:18333
      - LND_REST_PORT
      - LND_RPC_PORT
      - TLSPATH
      - TLSEXTRADOMAIN=lnd
    volumes:
      - ~/.chainpoint/gateway/.lnd:/root/.lnd:z
    networks:
      - chainpoint-gateway
    logging:
      driver: 'json-file'
      options:
        max-size: '1g'
        max-file: '5'

  # ln-accounting
  # Returns accounting reports in harmony format for lnd node
  ln-accounting:
    image: tierion/ln-accounting
    ports:
      - '9000'
    environment:
      NETWORK: ${NETWORK}
      LND_DIR: /root/.lnd
      LND_SOCKET: ${LND_SOCKET}
      ACCOUNTING_PORT: ${ACCOUNTING_PORT:-9000}
    volumes:
      - ~/.chainpoint/gateway/.lnd:/root/.lnd:ro
    networks:
      - chainpoint-gateway
