version: '3.7'

secrets:
  NODE_ETH_ADDRESS:
    external: true
  NODE_ETH_PRIVATE_KEY:
    external: true

services:

  chainpoint-registration:
    deploy:
      restart_policy:
        condition: none
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ./.env:/home/node/app/.env
    image: gcr.io/chainpoint-registry/github_chainpoint_chainpoint-node-src:${DOCKER_TAG:-latest}
    build: .
    command: ["/bin/bash", "-c", "/home/node/app/cli/run_start_registration.sh"]
    environment:
      NODE_ENV: ${NODE_ENV}
      NETWORK: ${NETWORK:-mainnet}
      HTTP_PORT: "${HTTP_PORT:-80}"
      NODE_ETH_ADDRESS: DOCKER-SECRET->NODE_ETH_ADDRESS
      NODE_ETH_PRIVATE_KEY: DOCKER-SECRET->NODE_ETH_PRIVATE_KEY
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_NODE_PRIVATE_URI: "${CHAINPOINT_NODE_PRIVATE_URI:-empty}"
      CHAINPOINT_NODE_REFLECT_PUBLIC_OR_PRIVATE: "${CHAINPOINT_NODE_REFLECT_PUBLIC_OR_PRIVATE}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      PRIVATE_NETWORK: ${PRIVATE_NETWORK:-false}
    secrets:
      - NODE_ETH_ADDRESS
      - NODE_ETH_PRIVATE_KEY
    tty: true
