version: '3.7'

networks:
  chainpoint-node:

secrets:

services:

  chainpoint-node:
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
      - ~/.chainpoint/node/data/rocksdb:/root/.chainpoint/node/data/rocksdb
      - ./.env:/home/node/app/.env
    image: gcr.io/chainpoint-registry/github_chainpoint_chainpoint-node-src:${DOCKER_TAG:-latest}
    build: .
    ports:
      - "80:80"
    networks:
      - chainpoint-node
    environment:
      NODE_ENV: ${NODE_ENV}
      NETWORK: ${NETWORK:-mainnet}
      HTTP_PORT: "${HTTP_PORT:-80}"
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
      CHAINPOINT_CORE_CONNECT_IP_LIST: "${CHAINPOINT_CORE_CONNECT_IP_LIST}"
      UV_THREADPOOL_SIZE: 128
    secrets:
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs.papertrailapp.com:27635"
        tag: "chp-node/{{.Name}}/{{.ID}}"
