/**
 * Copyright 2017 Tierion
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

// load environment variables
const env = require('./parse-env.js')

const _ = require('lodash')
const MerkleTools = require('merkle-tools')
const crypto = require('crypto')
const uuidTime = require('uuid-time')
const coreHosts = require('./core-hosts.js')
const BLAKE2s = require('blake2s-js')

// The redis connection used for all redis communication
// This value is set once the connection has been established
let redis = null

// The key used to generate the HMAC for POST /hash and /proofs requests
let HMAC_KEY = null

// An array of hash Data received awaiting aggregation
let HASHDATA = []

// the aggregation frequency
let AGG_FOR_CORE_INTERVAL_MS = 1000

// The merkle tools object for building trees and generating proof paths
const merkleTools = new MerkleTools()

/**
 * Converts proof path array output from the merkle-tools package
 * to a Chainpoint v3 ops array
 *
 * @param {proof object array} proof - The proof array generated by merkle-tools
 * @param {string} op - The hash type performed throughout merkle tree construction (sha-256, sha-512, sha-256-x2, etc.)
 * @returns {ops object array}
 */
function formatAsChainpointV3Ops (proof, op) {
  proof = proof.map((item) => {
    if (item.left) {
      return { l: item.left }
    } else {
      return { r: item.right }
    }
  })
  let ChainpointV3Ops = []
  for (let x = 0; x < proof.length; x++) {
    ChainpointV3Ops.push(proof[x])
    ChainpointV3Ops.push({ op: op })
  }
  return ChainpointV3Ops
}

// Build a merkle tree from HASHDATA hashes and submit the root to Core
async function aggregateAndSendToCoreAsync () {
  let hashDataForTree = HASHDATA.splice(0)

  // get an array of hashes from hashDataForTree
  let hashesForTree = hashDataForTree.reduce((prev, curr) => {
    return [...prev, ...curr.hashes]
  }, [])
  // get an array of unique ips from hashDataForTree
  let ipsForTree = _.uniq(hashDataForTree.map((hashDataItem) => {
    return hashDataItem.sourceIp
  }))

  if (hashesForTree.length > 0) {
    console.log(`INFO : Building aggregation tree with ${hashesForTree.length} hash(es) for this interval`)

    // clear the merkleTools instance to prepare for a new tree
    merkleTools.resetTree()

    // concatenate and hash the hash ids and hash values into new array
    let leaves = hashesForTree.map((hashObj) => {
      let hashIdBuffer = Buffer.from(`node_id:${hashObj.hash_id_node}`, 'utf8')
      let hashBuffer = Buffer.from(hashObj.hash, 'hex')
      let concatAndHashBuffer = crypto.createHash('sha256').update(Buffer.concat([hashIdBuffer, hashBuffer])).digest()
      return concatAndHashBuffer
    })

    // Add every hash in hashesForTree to new Merkle tree
    merkleTools.addLeaves(leaves)
    merkleTools.makeTree()

    let treeSize = merkleTools.getLeafCount()

    // Collect and store the merkle root, and proofs in an array to be used for proof generation
    let nodeAggregationData = {}
    nodeAggregationData.merkle_root = merkleTools.getMerkleRoot().toString('hex')

    let proofData = []
    for (let x = 0; x < treeSize; x++) {
      // push the hash_id and corresponding proof onto the array, inserting the UUID concat/hash step at the beginning
      let proofDataItem = {}
      proofDataItem.hash_id = hashesForTree[x].hash_id_node
      proofDataItem.hash = hashesForTree[x].hash
      let partialProofPath = merkleTools.getProof(x)
      partialProofPath.unshift({ left: `node_id:${hashesForTree[x].hash_id_node}` })
      proofDataItem.partial_proof_path = formatAsChainpointV3Ops(partialProofPath, 'sha-256')
      proofData.push(proofDataItem)
    }
    nodeAggregationData.proof_data = proofData

    // submit merkle root to Core
    try {
      let hash = crypto.createHmac('sha256', HMAC_KEY)
      let hmac = hash.update(env.NODE_TNT_ADDRESS).digest('hex')
      let submitResult = await submitHashToCoreAsync(nodeAggregationData.merkle_root, ipsForTree, hmac)

      // validate BLAKE2s
      let hashTimestampMS = parseInt(uuidTime.v1(submitResult.hash_id))
      let h = new BLAKE2s(5, { personalization: Buffer.from('CHAINPNT') })
      let hashStr = [
        hashTimestampMS.toString(),
        hashTimestampMS.toString().length,
        submitResult.hash,
        submitResult.hash.length,
        submitResult.nist,
        submitResult.nist.length
      ].join(':')
      h.update(Buffer.from(hashStr))
      let expectedData = Buffer.concat([Buffer.from([0x01]), h.digest()]).toString('hex')
      let embeddedData = submitResult.hash_id.slice(24)
      if (embeddedData !== expectedData) {
        throw new Error('Hash ID from Core refused: Cannot validate BLAKE2s embedded data')
      }

      nodeAggregationData.processing_hints = submitResult.processing_hints
      nodeAggregationData.hash_id_core = submitResult.hash_id
      // store nodeAggregationData object for later use when generating proofs
      let newKey = `${env.CORE_SUBMISSION_KEY_PREFIX}:${nodeAggregationData.hash_id_core}`
      let dataJSON = JSON.stringify(nodeAggregationData)
      try {
        await redis.setAsync(newKey, dataJSON, 'EX', env.PROOF_EXPIRE_MINUTES * 60)
      } catch (error) {
        throw new Error(`Could not save proof to Redis for ${newKey}`)
      }

      // write hash_id_node lookup to redis for each hash_id_node
      try {
        let currentCoreHost = await coreHosts.getCurrentCoreHostAsync()
        for (let x = 0; x < nodeAggregationData.proof_data.length; x++) {
          let newKey = `${env.HASH_NODE_LOOKUP_KEY_PREFIX}:${nodeAggregationData.proof_data[x].hash_id}`
          let dataString = `${nodeAggregationData.hash_id_core}:${currentCoreHost}`
          await redis.setAsync(newKey, dataString, 'EX', env.PROOF_EXPIRE_MINUTES * 60)
        }
      } catch (error) {
        throw new Error(`Could not write to hash_id lookup table for key: ${newKey}`)
      }

      console.log(`INFO : Hash submitted to Core: hash_id_core: ${nodeAggregationData.hash_id_core} remaining credits: ${submitResult.tnt_credit_balance}`)
    } catch (error) {
      console.error(`ERROR : Could not submit hash to Core: ${error.message}`)
    }
  }
}
// run aggregateToCore() at a regular interval
setInterval(aggregateAndSendToCoreAsync, AGG_FOR_CORE_INTERVAL_MS)

async function submitHashToCoreAsync (hash, ipArray, hmac) {
  let options = {
    headers: {
      'Content-Type': 'application/json',
      'tnt-address': env.NODE_TNT_ADDRESS
    },
    auth: {
      'bearer': hmac
    },
    method: 'POST',
    uri: `/hashes`,
    body: { hash: hash, ips: ipArray },
    json: true,
    gzip: true,
    resolveWithFullResponse: true
  }

  let response
  try {
    response = await coreHosts.coreRequestAsync(options)
  } catch (error) {
    // check for error as a result of Core NTP time being off
    if (error.statusCode === 500 && error.message === 'Bad NTP time') throw new Error('ERROR : Bad NTP time')
    if (error.statusCode) throw new Error(`ERROR : Invalid response : ${error.statusCode}`)
    throw new Error(`ERROR : No response received on POST hashes`)
  }

  let result = {
    hash_id: response.hash_id,
    hash: response.hash,
    nist: response.nist,
    processing_hints: response.processing_hints,
    tnt_credit_balance: response.tnt_credit_balance
  }
  return result
}

module.exports = {
  addHashData: (hashArray, sourceIp) => { HASHDATA.push({ hashes: hashArray, sourceIp: sourceIp }) },
  setRedis: (redisClient) => {
    coreHosts.setRedis(redisClient)
    redis = redisClient
  },
  setHmacKey: (hmacKey) => { HMAC_KEY = hmacKey }
}
